bsp-test-helper: fixed check runlevel
Signed-off-by: Mohamad Noor Alim Hussin <mohamad.noor.alim.hussin@intel.com>

diff --git a/meta/lib/oeqa/runtime/files/bsp-test-helper b/meta/lib/oeqa/runtime/files/bsp-test-helper
--- a/meta/lib/oeqa/runtime/files/bsp-test-helper
+++ b/meta/lib/oeqa/runtime/files/bsp-test-helper
@@ -117,25 +117,51 @@ case "$1" in
         fi
         ;;
     -r|--runlevel)
-        level=`runlevel | awk -F ' ' '{print $2}'`
-        echo "[DEBUG]: commandline: runlevel | runlevel | awk -F ' ' '{print $2}'" 2>&1 | tee -a $LOG_FILE > /dev/null
-        if [[ "$2" == "3" || "$2" == "5" ]]; then
-            if [[ "$level" == "3" && "$level" == "$2" ]]; then
-                echo "[DEBUG]: Test runlevel 3"  2>&1 | tee -a $LOG_FILE
-                echo "[INFO]: System start with runlevel: $level"$'\n' 2>&1 | tee -a $LOG_FILE
-                exit 0
-            elif [[ "$level" == "5" && "$level" == "$2" ]]; then
-                echo "[DEBUG]: Test runlevel 5" 2>&1 | tee -a $LOG_FILE > /dev/null
-                echo "[INFO]: System start with runlevel: $level"$'\n' 2>&1 | tee -a $LOG_FILE
-                exit 0
-            else
-                echo "[INFO]: System did not start with runlevel: $2"$'\n' 2>&1 | tee -a $LOG_FILE
+        level=`who -r | awk -F ' ' '{ print $1 $2 }'`
+        echo "[DEBUG]: commandline: level=who -r | awk -F ' ' '{ print \$\1 \$\2 }' 2>&1 | tee -a $LOG_FILE > /dev/null"
+        case $2 in
+            3)
+                if [[ $level == "run-level3" ]]; then
+                    echo "[DEBUG]: Test runlevel 3"  2>&1 | tee -a $LOG_FILE
+                    echo "[INFO]: System start with runlevel: $level"$'\n' 2>&1 | tee -a $LOG_FILE
+                    exit 0
+                else
+                    echo "[INFO]: System did not start with runlevel: $2"$'\n' 2>&1 | tee -a $LOG_FILE
+                    exit 1
+                fi
+            ;;
+            5)
+                if [[ $level == "run-level5" ]]; then
+                    echo "[DEBUG]: Test runlevel 5"  2>&1 | tee -a $LOG_FILE
+                    echo "[INFO]: System start with runlevel: $level"$'\n' 2>&1 | tee -a $LOG_FILE
+                    exit 0
+                else
+                    echo "[INFO]: System did not start with runlevel: $2"$'\n' 2>&1 | tee -a $LOG_FILE
+                    exit 1
+                fi
+            ;;
+            *)
+                echo "[ERROR]: Runlevel other than 3 & 5 are not allowed."$'\n' 2>&1 | tee -a $LOG_FILE
                 exit 1
-            fi
-        else
-            echo "[ERROR]: Runlevel other than 3 & 5 are not allowed."$'\n' 2>&1 | tee -a $LOG_FILE
-            exit 1
-        fi
+            ;;
+        esac
+        #if [[ "$2" == "3" || "$2" == "5" ]]; then
+        #    if [[ "$level" == "3" && "$level" == "$2" ]]; then
+        #        echo "[DEBUG]: Test runlevel 3"  2>&1 | tee -a $LOG_FILE
+        #        echo "[INFO]: System start with runlevel: $level"$'\n' 2>&1 | tee -a $LOG_FILE
+        #        exit 0
+        #    elif [[ "$level" == "5" && "$level" == "$2" ]]; then
+        #        echo "[DEBUG]: Test runlevel 5" 2>&1 | tee -a $LOG_FILE > /dev/null
+        #        echo "[INFO]: System start with runlevel: $level"$'\n' 2>&1 | tee -a $LOG_FILE
+        #        exit 0
+        #    else
+        #        echo "[INFO]: System did not start with runlevel: $2"$'\n' 2>&1 | tee -a $LOG_FILE
+        #        exit 1
+        #    fi
+        #else
+        #    echo "[ERROR]: Runlevel other than 3 & 5 are not allowed."$'\n' 2>&1 | tee -a $LOG_FILE
+        #    exit 1
+        #fi
         ;;
     -X| --test-xorg)
          XORG=`ps -ef | grep Xorg`
