scripts/board_config: remove configure buildbot-worker on DUT
Signed-off-by: Mohamad Noor Alim Hussin <mohamad.noor.alim.hussin@intel.com>

diff --git a/scripts/board_config b/scripts/board_config
--- a/scripts/board_config
+++ b/scripts/board_config
@@ -31,17 +31,17 @@ done
 echo "[  INFO  ] Install netifaces"
 pip3 install --proxy=$http_proxy netifaces
 
-echo "[  INFO  ] Install buildbot-worker"
-pip3 install --proxy=$http_proxy buildbot-worker
-git clone https://git.yoctoproject.org/git/yocto-autobuilder2
-git clone https://git.yoctoproject.org/git/yocto-autobuilder-helper
-buildbot-worker create-worker --umask=0o22 ~/yocto-worker $YOCTO_CONTROLLER `hostname` $BUILDBOT_PASS
-buildbot-worker start ~/yocto-worker
-if [[ $? -eq 0 ]]; then
-    echo "[  OK  ] Buildbot-worker start successfully"
-else
-   echo "[  ERROR  ] Unable to start buildbot-worker"
-fi
+#echo "[  INFO  ] Install buildbot-worker"
+#pip3 install --proxy=$http_proxy buildbot-worker
+#git clone https://git.yoctoproject.org/git/yocto-autobuilder2
+#git clone https://git.yoctoproject.org/git/yocto-autobuilder-helper
+#buildbot-worker create-worker --umask=0o22 ~/yocto-worker $YOCTO_CONTROLLER `hostname` $BUILDBOT_PASS
+#buildbot-worker start ~/yocto-worker
+#if [[ $? -eq 0 ]]; then
+#    echo "[  OK  ] Buildbot-worker start successfully"
+#else
+#   echo "[  ERROR  ] Unable to start buildbot-worker"
+#fi
 
 if [[ ! -d "/srv/data" ]]; then
     mkdir -p /srv/data
