board_config: Fix NFS mount by making as argument
To run board_config, NFSSERVER argument need to pass.
Example,

./board_config nfsserver.com

Signed-off-by: Mohamad Noor Alim Hussin <mohamad.noor.alim.hussin@intel.com>

diff --git a/scripts/board_config b/scripts/board_config
--- a/scripts/board_config
+++ b/scripts/board_config
@@ -3,6 +3,7 @@
 CONF_DIR="/srv/data/LAVA/config"
 LAVA_DIR=$(ls / | grep lava)
 LAVA_PROXY="/$LAVA_DIR/bin/lava-proxy"
+NFSSERVER=$1
 
 source $LAVA_PROXY
 echo "[  INFO  ] Set proxy"
@@ -50,7 +51,13 @@ else
     echo "[  INFO  ] Directory /srv/data exists"
 fi
 echo "[  INFO  ] Mount to nfs server"
-mount -o rw,hard,intr nfsserver:/srv/data /srv/data
+mount -o rw,hard,intr $NFSSERVER:/srv/data /srv/data
+
+if [[ $? -eq 0 ]]; then
+    echo "[  OK  ] Successfully mount to nfs server"
+else
+    echo "[  ERROR  ] Unable to mount to nfs server"
+fi
 
 echo "[  INFO  ] Set hostname"
 sed -i "s/localhost.localdomain/`hostname`/g" /etc/hosts
@@ -66,25 +73,6 @@ if [[ ! -z $nvme ]]; then
     fi
 else
     echo "[ INFO ] NVME partition is not exist"
-fi
-
-if [[ $? -eq 0 ]]; then
-    echo "[  OK  ] Successfully mount to nfs server"
-    #echo "[  INFO  ] Configure vncserver"
-    #mkdir ~/.vnc
-    #cp $CONF_DIR/vnc/vnc_config ~/.vnc/passwd;
-    #chmod 600 ~/.vnc/passwd
-    #vncserver :1; vncserver -kill :1
-    #rm ~/.vnc/xstartup
-    #cp $CONF_DIR/vnc/xstartup ~/.vnc/xstartup; chmod +x ~/.vnc/xstartup
-    #vncserver :1
-    #if [[ $? -eq 0 ]]; then
-    #    echo "[  OK  ] Vnc start at :1"
-    #else 
-    #    echo "[  ERROR  ] Unable to start vnc"
-    #fi
-else
-    echo "[  ERROR  ] Unable to mount to nfs server"
 fi
 
 #list_media=`ls /run/media`
